### ISSUE TITLE
Support for IdP discovery protocol

### ISSUE THREAD

**Issue by olavmrk** [simplesamlphp/SAML-tracer#3]
We should support the SAML 2.0 «Identity Provider Discovery Service Protocol and Profile».

Specification: http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-idp-discovery.pdf

**Comment by thijskh** [comment]
Basically the only way to recognise such requests is whether there's a `entityID` URL parameter present. This seems so a-specific that I think such discovery service protocol would flag too many requests as "SAML".

Since the SAML tracer already splits out the get parameters in the Parameters tab, you already have quite a decent overview of what happens in those requests, and I'm also not sure what additional processing SAML Tracer would do for discovery requests.

**Comment by tvdijen** [comment]
Closing this one;  I agree with Thijs. The IDP Disco request+response are shown in the tracer and to tag every request with an `entityID` URL-parameter is just too generic.
