### ISSUE TITLE
UI glitch: not all parameter keys are highlighted

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/SAML-tracer#83]
![afbeelding](https://github.com/simplesamlphp/SAML-tracer/assets/841045/3fde7224-7dcf-4161-9d80-92fc78509e3f)

I just noticed that not all parameter names are purple.

**Comment by thijskh** [comment]
The problem is the underscores. This display also uses the syntax highlighting from hljs with language “HTTP” which I guess is about http headers, not parsed parameters.

**Comment by tvdijen** [comment]
I _think_ the 'properties' language would be appropriate to use here

**Comment by khlr** [comment]
Hello Tim and Thijs!

Yep, I think you're absolutely right. The currently used language highlighting is certainly not the best choice. I probably chose that one back in the days, because it seemed appropriate to me and works in a lot of cases, but - as we see 😉 - not in all cases.
The properties language really seems to be worth a try, Tim!
