### ISSUE TITLE
FYI your manifest file in version 1.8.0 is still marked as 1.7.1

### ISSUE THREAD

**Issue by middleagedman** [simplesamlphp/SAML-tracer#94]
Also, the version isn't updated in the Firefox add-ons page either.

Thank you for this great extension!

**Comment by tvdijen** [comment]
That's for pointing out the manifest issue. v1.8.0 is indeed not released yet because Mozilla and Google have increased their demands on add-ons and we have yet to match their demands before we can upload the latest version to their add-on stores.

**Comment by tvdijen** [comment]
Seems there's progress on the blocking issue. I hope v1.8.0 can be officially released soon!
If you don't mind, I'm closing this issue now.  Thanks again for reporting!

**Comment by khlr** [comment]
I just uploaded version 1.8.0 to the Chrome Web Store and to AMO. 🚀
It may take some time until the new version is approved in the respective store.

One side note:
I locally edited the manifest.json for the AMO upload because it rejected version 1.8.0 and stated it was uploaded before. This is correct. Back in 12/2023 I tried to publish version 1.8.0 which I then had to cancel after the privacy policy blocker appeared in the Chrome Web Store... Hence version `1.8.0` is blocked now. I changed it to `1.8.0.0` if anyone wonders...

**Comment by tvdijen** [comment]
Was it refused by Mozilla, or what?  Just minutes after you posted this, I saw it released for Chrome, but Firefox is still at 1.7.1..

**Comment by khlr** [comment]
No, it's still awaiting review:

![image](https://github.com/user-attachments/assets/1725c3f3-c277-428e-9032-40626c91b01a)

Apparently the guys at AMO are taking things more seriously and a real person is actually still looking at it 😉

**Comment by tvdijen** [comment]
I was just going over the reviews on the Mozilla website and ran into a feature request to be able to maximize the add-on window. Do you know if that's even possible for a pop-up window?
